travis:
  secure:
    BINSTAR_TOKEN: FEyAvrV9GybidbtqpvjxOLMc5/Ejrj6Oo41hwbj0D+Nlh2eY6PVuFFobTax1cSX1TAlu1NjuPlBlA4kPyuCOc1aA1WiI7N9CzbwCTjYhUi24z9ZTwieqid8+eD14622BeQxf/ey97eI4d87xT9gbVxs5vtuYpS71H1By0mL5mNMrM2YgfiqZFHtDtOs+o8a+gKE/pGTpNNbFRsNc3zKPoPXDFlFlayKYgBIjWJpur4ZraQzFy4LbT5PoXsnuCXP3ubqvQq4j+O1sT6fGry5FqGc4I1mdleDuMAeTEGAMShlp67O3Kusy67k4zmDIA7DdLb6vl3fp32ZhVUbDESLyRMO0jwimNxoyEmyF+TZbFNFIwyJKCVBgpGMb/ZtuEKwdBnvnMfZAhzY/EaeqXjDJedXYMAIY1cb9Pu4CqNrcexwqIMovEWZMEMCI746HQUlyOWT4szp8Kjh5wLz7/XzcSww3Led5Lp914XNsExQO84rYFesiibr4LJl8mILbFdBH8R6o2TsY1UmkHdQ2cbsmfOnryqJi0DozaQi80fdLTi4DZoJQmpqIXfu+yIZjkJsnD6a5YlLQc88U8Gjbrv05WAQOky+CCv3p/0ktB2KnFCF/QzxYlMin2dkkZi4IcKeWScMGvJGCfDGSGvZ1WG5Ojd8Mtj+VEjfieD7HsC16n0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
