travis:
  secure:
    BINSTAR_TOKEN: dFrX6PipKVaZ6dOb880BDw7gVouXJvXIlcieYYjU4CTkPGDoolMNFISZ0zJlA2VwQr7qMYmr7fV8wDhdF/QNrcnTYzmqTtmX6wLcf+myo5iW/8wTCu5SVnOUSO7J6pKfvzQrrXMHKSYs4KMkvhP26o+ASoqYULXbFuzGY7Pv+oNVgws/wRmn36gHV8/0urkWm5GlxTRmuTURl+sUMRUph3H1gCrNNxsfTE54XYkE2y4WqspzO0OQ0t8adDFHDsRlh84JmiOn3f5GPJ0sZhClegdxea1bRJ0dIaxjMgBdJ3hxRL6vJGXHzy5j2C+ExRPx5Zwmc4DP0gMQGdRdIZyrFqOIdnDTUdqwX7oz3P179+P/CAcIljG2E+6ZcqZSfNXIrF3v9Do56PFKUo+i+a8etqW0/fGvKBCRV1dTxt93SZWS0M3lme4z6uuhLwWcU0mi+84pAB80tHT9xcYnusDQPbPBC6bVPD7hZaS9au7tgMRL2iLoQdkK2VLIqaiVDYtv9/FWrW32IyFIbm7n6D89SNHZgNtr7M6DSgLr2YcXZ0yUwWOOHSmf9iYvId5wRLdWWRnuC8lDJd+m0SzKPZyEa1n8roNwkLMQc/5sujuXMa4AK8kChHeNddUs5Jan0a72EIbxLQHjpxEoznQa/56bfOHHr1QwrS3zLYHFHM9ba2M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
